---
- name: Ensure basic packages are installed
  package:
    name:
      - vim
      - curl
      - wget
      - git
    state: present

- name: Ensure timezone is set
  timezone:
    name: Asia/Kuala_Lumpur
